export const COINS = Object.freeze({
  A_GAME: { coin: 'A_GAME', name: 'A-Game', tier: 4 },
  ALL_IN: { coin: 'ALL_IN', name: 'All-In', tier: 5 },
  ANTE: { coin: 'ANTE', name: 'Ante', tier: 7 },
  APOLLO: { coin: 'APOLLO', name: 'Apollo', tier: 2 },
  ATLANTIS: { coin: 'ATLANTIS', name: 'Atlantis', tier: 6 },
  AURIC: { coin: 'AURIC', name: 'Auric', tier: 4 },
  AZURITE: { coin: 'AZURITE', name: 'Azurite', tier: 7 },
  BLACKOUT: { coin: 'BLACKOUT', name: 'Blackout', tier: 6 },
  BLUE_CHIP: { coin: 'BLUE_CHIP', name: 'Blue Chip', tier: 6 },
  BUBBLEGUM: { coin: 'BUBBLEGUM', name: 'Bubblegum', tier: 5 },
  BULLSEYE: { coin: 'BULLSEYE', name: 'Bullseye', tier: 4 },
  CALIBRATE: { coin: 'CALIBRATE', name: 'Calibrate', tier: 6 },
  COBALT: { coin: 'COBALT', name: 'Cobalt', tier: 7 },
  CONROI: { coin: 'CONROI', name: 'Conroi', tier: 7 },
  CONSENSUS: { coin: 'CONSENSUS', name: 'Consensus', tier: 6 },
  COPPER: { coin: 'COPPER', name: 'Copper', tier: 7 },
  CRIMSON: { coin: 'CRIMSON', name: 'Crimson', tier: 3 },
  CYNOSURE: { coin: 'CYNOSURE', name: 'Cynosure', tier: 6 },
  ECLIPSE: { coin: 'ECLIPSE', name: 'Eclipse', tier: 4 },
  EMERALD: { coin: 'EMERALD', name: 'Emerald', tier: 6 },
  EVERGREEN: { coin: 'EVERGREEN', name: 'Evergreen', tier: 5 },
  GOLD: { coin: 'GOLD', name: 'Gold', tier: 5 },
  HIEROGLYPHIC: { coin: 'HIEROGLYPHIC', name: 'Hieroglyphic', tier: 2 },
  INTERSTELLAR: { coin: 'INTERSTELLAR', name: 'Interstellar', tier: 1 },
  IRIDESCENT: { coin: 'IRIDESCENT', name: 'Iridescent', tier: 4 },
  JASPER: { coin: 'JASPER', name: 'Jasper', tier: 5 },
  JUBILEE: { coin: 'JUBILEE', name: 'Jubilee', tier: 5 },
  JURASSIC: { coin: 'JURASSIC', name: 'Jurassic', tier: 5 },
  KOI: { coin: 'KOI', name: 'Koi', tier: 1 },
  LEPIDOLITE: { coin: 'LEPIDOLITE', name: 'Lepidolite', tier: 6 },
  ORNATE: { coin: 'ORNATE', name: 'Ornate', tier: 7 },
  PLATINUM: { coin: 'PLATINUM', name: 'Platinum', tier: 6 },
  POMPEI: { coin: 'POMPEI', name: 'Pompeii', tier: 3 },
  PORCELAIN: { coin: 'PORCELAIN', name: 'Porcelain', tier: 3 },
  RASPBERRY: { coin: 'RASPBERRY', name: 'Raspberry', tier: 7 },
  RHODIUM: { coin: 'RHODIUM', name: 'Rhodium', tier: 7 },
  ROYAL: { coin: 'ROYAL', name: 'Royal', tier: 5 },
  RUBY: { coin: 'RUBY', name: 'Ruby', tier: 7 },
  SERAC: { coin: 'SERAC', name: 'Serac', tier: 6 },
  SHALE: { coin: 'SHALE', name: 'Shale', tier: 6 },
  SILVER: { coin: 'SILVER', name: 'Silver', tier: 7 },
  HELIOS: { coin: 'HELIOS', name: 'Helios', tier: 3 },
  STEREOSCOPIC: { coin: 'STEREOSCOPIC', name: 'Stereoscopic', tier: 4 },
  STRATOSPHERE: { coin: 'STRATOSPHERE', name: 'Stratosphere', tier: 7 },
  TRIANGULUM: { coin: 'TRIANGULUM', name: 'Triangulum', tier: 5 },
  TUMBAGA: { coin: 'TUMBAGA', name: 'Tumbaga', tier: 6 },
  TWO_TONE: { coin: 'TWO_TONE', name: 'Two-Tone', tier: 7 },
  VERDIGRIS: { coin: 'VERDIGRIS', name: 'Verdigris', tier: 7 },
  VINYL: { coin: 'VINYL', name: 'Vinyl', tier: 5 },
  VOLUTION: { coin: 'VOLUTION', name: 'Volution', tier: 5 },
})

export const TIERS = [
  [COINS.INTERSTELLAR, COINS.KOI],
  [COINS.APOLLO, COINS.HIEROGLYPHIC],
  [COINS.CRIMSON, COINS.HELIOS, COINS.POMPEI, COINS.PORCELAIN],
  [COINS.A_GAME, COINS.AURIC, COINS.BULLSEYE, COINS.ECLIPSE, COINS.IRIDESCENT, COINS.STEREOSCOPIC],
  [
    COINS.ALL_IN,
    COINS.BUBBLEGUM,
    COINS.EVERGREEN,
    COINS.GOLD,
    COINS.JASPER,
    COINS.JUBILEE,
    COINS.JURASSIC,
    COINS.ROYAL,
    COINS.TRIANGULUM,
    COINS.VINYL,
    COINS.VOLUTION,
  ],
  [
    COINS.ATLANTIS,
    COINS.BLACKOUT,
    COINS.BLUE_CHIP,
    COINS.CALIBRATE,
    COINS.CONSENSUS,
    COINS.CYNOSURE,
    COINS.EMERALD,
    COINS.LEPIDOLITE,
    COINS.PLATINUM,
    COINS.SERAC,
    COINS.SHALE,
    COINS.TUMBAGA,
  ],
  [
    COINS.ANTE,
    COINS.AZURITE,
    COINS.COBALT,
    COINS.CONROI,
    COINS.COPPER,
    COINS.ORNATE,
    COINS.RASPBERRY,
    COINS.RHODIUM,
    COINS.RUBY,
    COINS.SILVER,
    COINS.STRATOSPHERE,
    COINS.TWO_TONE,
    COINS.VERDIGRIS,
  ],
]
