const LP_ICONS = Object.freeze({
  AVAX: '/images/lp-icons/AVAX.png',
  A_GAME: '/images/lp-icons/A-Game plain.png',
  ALL_IN: '/images/lp-icons/All-In plain.png',
  ANTE: '/images/lp-icons/Ante plain.png',
  APOLLO: '/images/lp-icons/Apollo plain.png',
  ATLANTIS: '/images/lp-icons/Atlantis plain.png',
  AURIC: '/images/lp-icons/Auric plain.png',
  AZURITE: '/images/lp-icons/Azurite plain.png',
  BLACKOUT: '/images/lp-icons/Blackout plain.png',
  BLUE_CHIP: '/images/lp-icons/Blue Chip plain.png',
  BUBBLEGUM: '/images/lp-icons/Bubblegum plain.png',
  BULLSEYE: '/images/lp-icons/Bullseye plain.png',
  CALIBRATE: '/images/lp-icons/Calibrate plain.png',
  COBALT: '/images/lp-icons/Cobalt plain.png',
  CONROI: '/images/lp-icons/Conroi plain.png',
  CONSENSUS: '/images/lp-icons/Consensus plain.png',
  COPPER: '/images/lp-icons/Copper plain.png',
  CRIMSON: '/images/lp-icons/Crimson plain.png',
  CYNOSURE: '/images/lp-icons/Cynosure plain.png',
  ECLIPSE: '/images/lp-icons/Eclipse plain.png',
  EMERALD: '/images/lp-icons/Emerald plain.png',
  EVERGREEN: '/images/lp-icons/Evergreen plain.png',
  GOLD: '/images/lp-icons/Gold plain.png',
  HIEROGLYPHIC: '/images/lp-icons/Hieroglyphic plain.png',
  INTERSTELLAR: '/images/lp-icons/Interstellar plain.png',
  IRIDESCENT: '/images/lp-icons/Iridescent plain.png',
  JASPER: '/images/lp-icons/Jasper plain.png',
  JUBILEE: '/images/lp-icons/Jubilee plain.png',
  JURASSIC: '/images/lp-icons/Jurassic plain.png',
  KOI: '/images/lp-icons/Koi plain.png',
  LEPIDOLITE: '/images/lp-icons/Lepidolite plain.png',
  ORNATE: '/images/lp-icons/Ornate plain.png',
  PLATINUM: '/images/lp-icons/Platinum plain.png',
  POMPEI: '/images/lp-icons/Pompei plain.png',
  PORCELAIN: '/images/lp-icons/Porcelain plain.png',
  RASPBERRY: '/images/lp-icons/Raspberry plain.png',
  RHODIUM: '/images/lp-icons/Rhodium plain.png',
  ROYAL: '/images/lp-icons/Royal plain.png',
  RUBY: '/images/lp-icons/Ruby plain.png',
  SERAC: '/images/lp-icons/Serac plain.png',
  SHALE: '/images/lp-icons/Shale plain.png',
  SILVER: '/images/lp-icons/Silver plain.png',
  HELIOS: '/images/lp-icons/Helios plain.png',
  STEREOSCOPIC: '/images/lp-icons/Stereoscopic plain.png',
  STRATOSPHERE: '/images/lp-icons/Stratosphere plain.png',
  TRIANGULUM: '/images/lp-icons/Triangulum plain.png',
  TUMBAGA: '/images/lp-icons/Tumbaga plain.png',
  TWO_TONE: '/images/lp-icons/Two-Tone plain.png',
  VERDIGRIS: '/images/lp-icons/Verdigris plain.png',
  VINYL: '/images/lp-icons/Vinyl plain.png',
  VOLUTION: '/images/lp-icons/Volution plain.png',
  NoIcon: '/images/no-image.png',
})

export default LP_ICONS;